// Pure helpers for the generator — no side effects, so they're unit-testable
// without the native toolchain. The CLI (bin/gen.mjs) wires these to fs/exec.

import { readFileSync } from "node:fs";

const APP_ID_RE = /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/i;

export function readJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

/**
 * Validate + normalize an app's brand.json.
 * Required: appId (reverse-DNS), appName. Returns a frozen normalized object.
 */
export function validateBrand(brand, appName) {
  const where = `apps/${appName ?? "?"}/brand.json`;
  if (!brand || typeof brand !== "object") throw new Error(`${where}: not an object`);
  if (typeof brand.appId !== "string" || !APP_ID_RE.test(brand.appId)) {
    throw new Error(`${where}: "appId" must be reverse-DNS (e.g. "ca.cobd.app.alpha"), got ${JSON.stringify(brand.appId)}`);
  }
  if (typeof brand.appName !== "string" || brand.appName.trim() === "") {
    throw new Error(`${where}: "appName" is required`);
  }
  return Object.freeze({
    appId: brand.appId,
    appName: brand.appName,
    // optional: theme color etc., passed through untouched
    extra: brand.extra ?? {},
  });
}

/** Validate a menu.json: an array of { label, target } items. */
export function validateMenu(menu, appName) {
  const where = `apps/${appName ?? "?"}/menu.json`;
  const items = Array.isArray(menu) ? menu : menu?.items;
  if (!Array.isArray(items)) throw new Error(`${where}: expected an array (or { items: [...] })`);
  items.forEach((it, i) => {
    if (typeof it?.label !== "string") throw new Error(`${where}[${i}]: "label" is required`);
    if (typeof it?.target !== "string") throw new Error(`${where}[${i}]: "target" is required`);
  });
  return items;
}

/**
 * Validate an app's seo.json: the page/site metadata the oister
 * shell needs beyond branding + nav. description/url/image are
 * required (no sane default); the rest is filled by @cobdfamily/
 * oister's renderApp from brand-derived or COBD defaults.
 */
export function validateSeo(seo, appName) {
  const where = `apps/${appName ?? "?"}/seo.json`;
  if (!seo || typeof seo !== "object") throw new Error(`${where}: not an object`);
  for (const key of ["description", "url", "image"]) {
    if (typeof seo[key] !== "string" || seo[key].trim() === "") {
      throw new Error(`${where}: "${key}" is required`);
    }
  }
  return seo;
}

/** Validate the top-level generator config. */
export function validateConfig(config) {
  if (typeof config?.capacitorVersion !== "string") throw new Error("generator.config.json: capacitorVersion required");
  const platforms = config.platforms ?? ["android", "ios"];
  for (const p of platforms) {
    if (p !== "android" && p !== "ios") throw new Error(`generator.config.json: unknown platform "${p}"`);
  }
  return { ...config, platforms };
}

/**
 * The ordered plan for regenerating one app. Returned as plain step descriptors
 * so the CLI can log them (and --dry-run can print them) before executing.
 * This is the canonical statement of approach D.
 */
export function planSteps({ config, app, brand }) {
  const ver = config.capacitorVersion;
  const platforms = config.platforms.join(", ");
  return [
    { id: "clean", desc: `wipe ${config.outDir}/${app} (native projects are disposable)` },
    { id: "build-web", desc: `build base web: ${config.base?.buildCommand || "(base not configured — see generator.config.json)"}` },
    { id: "assemble-web", desc: `copy base dist + overlay assets (menu.json, brand.json) into webDir; render index.html from brand/menu/seo via @cobdfamily/oister` },
    { id: "scaffold", desc: `write package.json (Capacitor pinned ${ver}) + capacitor.config.ts (appId=${brand.appId}, appName=${brand.appName})` },
    { id: "install", desc: `npm install in the ephemeral project` },
    { id: "cap-add", desc: `npx cap add ${platforms}` },
    { id: "overlay-native", desc: `apply shared native overlay (iOS Info.plist keys, Android permissions/manifest)` },
    { id: "assets", desc: `npx capacitor-assets generate (from apps/${app}/icon.png)` },
    { id: "cap-sync", desc: `npx cap sync` },
    { id: "build-sign", desc: `build + sign (CI): gradle (Android) / fastlane match + xcodebuild (iOS)` },
  ];
}

/** Render the ephemeral project's capacitor.config.ts from a brand. */
export function renderCapacitorConfig(brand) {
  return `import type { CapacitorConfig } from "@capacitor/cli";

// GENERATED by @cobdfamily/cobd-app-generator — do not edit; edit the app's brand.json.
const config: CapacitorConfig = {
  appId: ${JSON.stringify(brand.appId)},
  appName: ${JSON.stringify(brand.appName)},
  webDir: "www",
};

export default config;
`;
}

/** Render the ephemeral project's package.json with Capacitor pinned. */
export function renderProjectPackageJson(brand, config) {
  const v = `^${config.capacitorVersion}`;
  const pkg = {
    name: brand.appId.replace(/\./g, "-"),
    version: "0.0.0",
    private: true,
    description: `Generated Capacitor app ${brand.appName} (${brand.appId}). Do not edit — regenerated by @cobdfamily/cobd-app-generator.`,
    dependencies: {
      "@capacitor/android": v,
      "@capacitor/core": v,
      "@capacitor/ios": v,
    },
    devDependencies: {
      "@capacitor/assets": "latest",
      "@capacitor/cli": v,
    },
  };
  return JSON.stringify(pkg, null, 2) + "\n";
}
